name: Publish NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Dutchskull.Aspire.Git/Dutchskull.Aspire.Git.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Dutchskull.Aspire.Git/Dutchskull.Aspire.Git.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output ./nupkg src/Dutchskull.Aspire.Git/Dutchskull.Aspire.Git.csproj -p:NuspecFile=.nuspec

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
