name: Publish NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Aspire.Git/Aspire.Git.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Aspire.Git/Aspire.Git.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output ./nupkg src/Aspire.Git/Aspire.Git.csproj
        
      - name: Rename package with Dutchskull prefix
        run: |
          for file in ./nupkg/*.nupkg; do
            base_name=$(basename $file)
            mv $file ./nupkg/Dutchskull.$base_name
          done
  
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
